/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BoneRouteImport } from './routes/bone'
import { Route as IndexRouteImport } from './routes/index'

const BoneRoute = BoneRouteImport.update({
  id: '/bone',
  path: '/bone',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bone': typeof BoneRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bone': typeof BoneRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bone': typeof BoneRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bone'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bone'
  id: '__root__' | '/' | '/bone'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoneRoute: typeof BoneRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/bone': {
      id: '/bone'
      path: '/bone'
      fullPath: '/bone'
      preLoaderRoute: typeof BoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoneRoute: BoneRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
